### ISSUE TITLE
mockData script freezing

### ISSUE THREAD

**Issue by gnom1gnom** [instamed/healthcare-payments-blockchain#2] opened 2019-10-02 12:09 UTC
OS: Ubuntu 18.04.3 LTS
Node: v8.11.4
npm: 5.6.0
hurl: 1.0.6

The _mockData_ task (_setup-mockdata.sh_) freezes after invoking first chaincode method. I was successful running the entire script only when I upgraded _"@worldsibu/hurley": "~1.0.0"_ to _1.1.1_ in the devDependencies.

**Comment by instameddevelopment** [comment] 2019-12-04 16:44
This issue is a duplicate of https://github.com/instamed/healthcare-payments-blockchain/issues/6

**Comment by instameddevelopment** [comment] 2019-12-04 16:47
Solved.

**Closed by instameddevelopment** 2019-12-04 16:47 UTC
